
class Hotel {
  String imageUrl;
  String name;
  String address;
  int price;
  double height;
  String category;
  String bossName;
  String bossPhone;
  double acreage;
  double mezzanine;
  int maxPeople;
  int waterPrice;
  String deposit;

  Hotel({
    required this.imageUrl,
    required this.name,
    required this.address,
    required this.price,
    required this.height,
    required this.category,
    required this.bossName,
    required this.bossPhone,
    required this.acreage,
    required this.mezzanine,
    required this.maxPeople,
    required this.waterPrice,
    required this.deposit,
  });
}

final List<Hotel> hotels = [
  Hotel(
    imageUrl: 'assets/images/image9.jpg',
    name: 'Tatarasuma',
    address: 'Inazuma Teyvat',
    price: 2300000,
    height: 200,
    category: 'Trend',
    bossName: 'Nguyễn Hoàng Thụ',
    bossPhone: '03442512454',
    acreage: 20.0,
    mezzanine: 10.0,
    maxPeople: 5,
    waterPrice: 30000,
    deposit: 'Đặt cọc trước 6 tháng, sau 6 tháng hoàn lại tiền cọc',
  ),
  Hotel(
    imageUrl: 'assets/images/image10.jpg',
    name: 'Seirai',
    address: 'Inazuma Teyvat',
    price: 2320000,
    height: 240,
    category: 'Recommend',
    bossName: 'Nguyễn Minh Thư',
    bossPhone: '0372231124',
    acreage: 23.0,
    mezzanine: 0.0,
    maxPeople: 3,
    waterPrice: 6000,
    deposit: 'Đặt cọc trước 3 tháng, sau 3 tháng hoàn lại tiền cọc',
  ),
  Hotel(
    imageUrl: 'assets/images/image11.jpg',
    name: 'Narukami',
    address: 'Inazuma Teyvat',
    price: 1900000,
    height: 180,
    category: 'Trend',
    bossName: 'Hoàng Hữu Chí',
    bossPhone: '0372231124',
    acreage: 23.0,
    mezzanine: 0.0,
    maxPeople: 4,
    waterPrice: 7000,
    deposit: 'Đặt cọc trước 1 tháng',
  ),
  Hotel(
    imageUrl: 'assets/images/image12.jfif',
    name: 'Yashiro',
    address: 'Inazuma Teyvat',
    price: 3400000,
    height: 220,
    category: 'top-search',
    bossName: 'Lê Chí Bình',
    bossPhone: '0372231124',
    acreage: 13.0,
    mezzanine: 4.0,
    maxPeople: 3,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 2 tháng',
  ),
  Hotel(
      imageUrl: 'assets/images/image2.jpg',
      name: 'Gate 7',
      address: 'One Piece',
      price: 2000000,
      height: 230,
      category: 'Featured',
      bossName: 'Lê Bình Phương',
      bossPhone: '0372521242',
      acreage: 18.0,
      mezzanine: 12.0,
      maxPeople: 3,
      waterPrice: 4000,
      deposit: 'Đặt cọc trước 4 tháng',
  ),
  Hotel(
      imageUrl: 'assets/images/image3.jpg',
      name: 'Waterfall',
      address: 'Teyvat',
      price: 4000000,
      height: 230,
      category: 'New',
      bossName: 'Nguyễn Chí Minh',
      bossPhone: '0372231124',
      acreage: 18.0,
      mezzanine: 8.0,
      maxPeople: 6,
      waterPrice: 45000,
      deposit: 'Đặt cọc trước 1 tháng',
  ),
  Hotel(
    imageUrl: 'assets/images/image3.jpg',
    name: 'Waterfall',
    address: 'Teyvat',
    price: 2500000,
    height: 230,
    category: 'New',
    bossName: 'Nguyễn Hoài Lợi',
    bossPhone: '0372231124',
    acreage: 15.0,
    mezzanine: 10.0,
    maxPeople: 5,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 1 tháng',
  ),
  Hotel(
    imageUrl: 'assets/images/image3.jpg',
    name: 'Waterfall',
    address: 'Teyvat',
    price: 2540000,
    height: 210,
    category: 'top-search',
    bossName: 'Nguyễn Phương',
    bossPhone: '0372231124',
    acreage: 23.0,
    mezzanine: 18.4,
    maxPeople: 6,
    waterPrice: 70000,
    deposit: 'Đặt cọc trước 8 tháng',
  ),
  Hotel(
    imageUrl: 'assets/images/image4.jpg',
    name: 'Liyue Harbor',
    address: 'Liyue Teyvat',
    price: 2930000,
    height: 214,
    category: 'Recommend',
    bossName: 'Đoàn Minh Dự',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
  ),
  Hotel(
    imageUrl: 'assets/images/image5.jpg',
    name: 'Thousand Winds Temple',
    address: 'Mondstad Teyvat',
    price: 1300000,
    height: 160,
    category: 'New',
    bossName: 'Nguyễn Chí Minh',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
  ),
  Hotel(
    imageUrl: 'assets/images/image6.jpg',
    name: 'Sangonomiya Shrine',
    address: 'Inazuma Teyvat',
    price: 1750000,
    height: 180,
    category: 'Featured',
    bossName: 'Lê Bảo',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
  ),
  Hotel(
    imageUrl: 'assets/images/image7.jpg',
    name: 'Fort Fujitou',
    address: 'Inazuma Teyvat',
    price: 1950000,
    height: 320,
    category: 'top-search',
    bossName: 'Lê Đình Trọng',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
  ),
  Hotel(
    imageUrl: 'assets/images/image8.jpg',
    name: 'Jakotsu Mine',
    address: 'Inazuma Teyvat',
    price: 1680000,
    height: 200,
    category: 'Recommend',
    bossName: 'Nguyễn Duy Phong',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
  ),
  Hotel(
    imageUrl: 'assets/images/image9.jpg',
    name: 'Bourou Village',
    address: 'Inazuma Teyvat',
    price: 1420000,
    height: 190,
    category: 'Featured',
    bossName: 'Phạm Chí Thoại',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
  ),
];