
class Motel {
  String id;
  List<String> imageUrl;
  String name;
  String address;
  int price;
  double height;
  List<String> tags;
  String bossName;
  String bossPhone;
  double acreage;
  double mezzanine;
  int maxPeople;
  int waterPrice;
  String deposit;
  String formality;
  double latitude;
  double longtitude;

  Motel({
    required this.id,
    required this.imageUrl,
    required this.name,
    required this.address,
    required this.price,
    required this.height,
    required this.tags,
    required this.bossName,
    required this.bossPhone,
    required this.acreage,
    required this.mezzanine,
    required this.maxPeople,
    required this.waterPrice,
    required this.deposit,
    required this.formality,
    required this.latitude,
    required this.longtitude,
  });
}

final List<Motel> hotels = [
  Motel(
    id: "motel1",
    imageUrl: [
      'assets/images/nhatro5.jpg',
      'assets/images/nhatro1.jpg',
      'assets/images/nhatro2.jpg',
      'assets/images/nhatro3.jpg',
      'assets/images/nhatro4.jpg',
      'assets/images/nhatro7.jpg',
    ],
    name: '02 Cống Quỳnh',
    address: 'phường Hòa Cường Nam, quận Cẩm lệ, Đà Nẵng',
    price: 2300000,
    height: 200,
    tags: ['Giá rẻ', 'Nhiều tiện ích'],
    bossName: 'Nguyễn Hoàng Thụ',
    bossPhone: '03442512454',
    acreage: 20.0,
    mezzanine: 10.0,
    maxPeople: 5,
    waterPrice: 30000,
    deposit: 'Đặt cọc trước 6 tháng, sau 6 tháng hoàn lại tiền cọc',
    formality: 'Không chung chủ',
    latitude: 16.0553,
    longtitude: 108.5212
  ),
  Motel(
    id: "motel2",
    imageUrl: [
      'assets/images/nhatro2.jpg',
      'assets/images/nhatro1.jpg',
      'assets/images/nhatro3.jpg',
      'assets/images/nhatro4.jpg',
      'assets/images/nhatro5.jpg',
      'assets/images/nhatro7.jpg',
    ],
    name: '124 Cách mạng tháng 8',
    address: 'Cẩm Lệ',
    price: 2320000,
    height: 240,
      tags: ['Giá rẻ', 'Nhiều tiện ích', 'Hỗ trợ đặt phòng'],
    bossName: 'Nguyễn Minh Thư',
    bossPhone: '0372231124',
    acreage: 23.0,
    mezzanine: 0.0,
    maxPeople: 3,
    waterPrice: 6000,
    deposit: 'Đặt cọc trước 3 tháng, sau 3 tháng hoàn lại tiền cọc',
    formality: 'Không chung chủ',
    latitude: 16.0653,
    longtitude: 108.1212
  ),
  Motel(
    id: "motel3",
    imageUrl: [
      'assets/images/nhatro3.jpg',
      'assets/images/nhatro2.jpg',
      'assets/images/nhatro1.jpg',
      'assets/images/nhatro4.jpg',
      'assets/images/nhatro5.jpg',
      'assets/images/nhatro7.jpg',
    ],
    name: '51 Lê Sát',
    address: 'Hòa Cường Nam, Hải Châu',
    price: 1900000,
    height: 180,
      tags: ['Giá rẻ', 'Nhiều tiện ích', 'Hỗ trợ đặt phòng', 'Không cần đặt cọc'],
    bossName: 'Hoàng Hữu Chí',
    bossPhone: '0372231124',
    acreage: 23.0,
    mezzanine: 0.0,
    maxPeople: 4,
    waterPrice: 7000,
    deposit: 'Đặt cọc trước 1 tháng',
    formality: 'Chung chủ',
    latitude: 16.0613,
    longtitude: 108.5515
  ),
  Motel(
    id: "motel4",
    imageUrl: [
      'assets/images/nhatro4.jpg',
      'assets/images/nhatro2.jpg',
      'assets/images/nhatro3.jpg',
      'assets/images/nhatro1.jpg',
      'assets/images/nhatro5.jpg',
      'assets/images/nhatro7.jpg',
    ],
    name: '551 Tố Hữu',
    address: 'Hải Châu',
    price: 3400000,
    height: 220,
    tags: ['Giá rẻ', 'Nhiều tiện ích', 'Hỗ trợ đặt phòng', 'Không cần đặt cọc'],
    bossName: 'Lê Chí Bình',
    bossPhone: '0372231124',
    acreage: 13.0,
    mezzanine: 4.0,
    maxPeople: 3,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 2 tháng',
    formality: 'Chung chủ',
    latitude: 16.0293,
    longtitude: 108.4512
  ),
  Motel(
    id: "motel5",
    imageUrl: [
      'assets/images/nhatro5.jpg',
      'assets/images/nhatro2.jpg',
      'assets/images/nhatro3.jpg',
      'assets/images/nhatro4.jpg',
      'assets/images/nhatro1.jpg',
      'assets/images/nhatro7.jpg',
    ],
    name: '214 Trưng Nữ Vương',
    address: 'Liên Chiểu',
    price: 2000000,
    height: 230,
    tags: ['Giá rẻ', 'Không cần đặt cọc'],
    bossName: 'Lê Bình Phương',
    bossPhone: '0372521242',
    acreage: 18.0,
    mezzanine: 12.0,
    maxPeople: 3,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 4 tháng',
    formality: 'Chung chủ',
    latitude: 16.0651,
    longtitude: 108.5712
  ),
  Motel(
    id: "motel6",
    imageUrl: [
      'assets/images/nhatro2.jpg',
      'assets/images/nhatro3.jpg',
      'assets/images/nhatro4.jpg',
      'assets/images/nhatro5.jpg',
      'assets/images/nhatro1.jpg',
      'assets/images/nhatro7.jpg',
    ],
    name: '95 Cống Quỳnh',
    address: 'Cẩm Lệ',
    price: 4000000,
    height: 230,
    tags: ['Giá rẻ', 'Phản hồi tốt', 'Hỗ trợ đặt phòng', 'Không cần đặt cọc'],
    bossName: 'Nguyễn Chí Minh',
    bossPhone: '0372231124',
    acreage: 18.0,
    mezzanine: 8.0,
    maxPeople: 6,
    waterPrice: 45000,
    deposit: 'Đặt cọc trước 1 tháng',
    formality: 'Căn hộ',
    latitude: 16.0253,
    longtitude: 108.2212
  ),
  Motel(
    id: "motel7",
    imageUrl: [
      'assets/images/nhatro8.png',
      'assets/images/nhatro9.jpg',
      'assets/images/nhatro10.jpg',
      'assets/images/nhatro11.jpg',
      'assets/images/nhatro12.jpg',
      'assets/images/nhatro13.jpg',
      'assets/images/nhatro14.jpg',
      'assets/images/nhatro15.jpg',
    ],
    name: '02 Lê Hữu Trác',
    address: 'Thanh Khê',
    price: 2500000,
    height: 230,
      tags: ['Giá rẻ', 'Nhiều tiện ích', 'Phản hồi tốt', 'Không cần đặt cọc'],
    bossName: 'Nguyễn Hoài Lợi',
    bossPhone: '0372231124',
    acreage: 15.0,
    mezzanine: 10.0,
    maxPeople: 5,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 1 tháng',
    formality: 'Căn hộ',
    latitude: 16.0299,
    longtitude: 108.8812
  ),
  Motel(
    id: "motel8",
    imageUrl: [
      'assets/images/nhatro8.png',
      'assets/images/nhatro9.jpg',
      'assets/images/nhatro10.jpg',
      'assets/images/nhatro11.jpg',
      'assets/images/nhatro12.jpg',
      'assets/images/nhatro13.jpg',
      'assets/images/nhatro14.jpg',
      'assets/images/nhatro15.jpg',
    ],
    name: '95 Trần Hưng Đạo',
    address: 'Thanh Khê',
    price: 2540000,
    height: 210,
      tags: ['Giá rẻ', 'Nhiều tiện ích', 'Hỗ trợ đặt phòng'],
    bossName: 'Nguyễn Phương',
    bossPhone: '0372231124',
    acreage: 23.0,
    mezzanine: 18.4,
    maxPeople: 6,
    waterPrice: 70000,
    deposit: 'Đặt cọc trước 8 tháng',
    formality: 'Căn hộ',
    latitude: 16.07853,
    longtitude: 108.242212
  ),
  Motel(
    id: "motel9",
    imageUrl: [
      'assets/images/nhatro13.jpg',
      'assets/images/nhatro8.png',
      'assets/images/nhatro9.jpg',
      'assets/images/nhatro14.jpg',
      'assets/images/nhatro10.jpg',
      'assets/images/nhatro11.jpg',
      'assets/images/nhatro12.jpg',
      'assets/images/nhatro15.jpg',
    ],
    name: '57 Trưng Trắc',
    address: 'Thanh Khê',
    price: 2930000,
    height: 214,
    tags: ['Giá rẻ', 'Nhiều tiện ích'],
    bossName: 'Đoàn Minh Dự',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
    formality: 'Căn hộ',
    latitude: 16.025153,
    longtitude: 108.225212
  ),
  Motel(
    id: "motel10",
    imageUrl: [
      'assets/images/nhatro15.jpg',
      'assets/images/nhatro12.jpg',
      'assets/images/nhatro10.jpg',
      'assets/images/nhatro8.png',
      'assets/images/nhatro9.jpg',
      'assets/images/nhatro11.jpg',
      'assets/images/nhatro13.jpg',
      'assets/images/nhatro14.jpg',
    ],
    name: '884 Lê Duẩn',
    address: 'Ngũ Hành Sơn',
    price: 1300000,
    height: 160,
      tags: ['Giá rẻ', 'Nhiều tiện ích', 'Không cần đặt cọc'],
    bossName: 'Nguyễn Chí Minh',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
    formality: 'Ký túc xá',
    latitude: 16.028753,
    longtitude: 108.223212
  ),
  Motel(
    id: "motel11",
    imageUrl: [
      'assets/images/nhatro11.jpg',
      'assets/images/nhatro14.jpg',
      'assets/images/nhatro8.png',
      'assets/images/nhatro9.jpg',
      'assets/images/nhatro10.jpg',
      'assets/images/nhatro12.jpg',
      'assets/images/nhatro13.jpg',
      'assets/images/nhatro15.jpg',
    ],
    name: '66 Trần Hưng Đạo',
    address: 'Liên Chiểu',
    price: 1750000,
    height: 180,
    tags: ['Giá rẻ', 'Không cần đặt cọc'],
    bossName: 'Lê Bảo',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
    formality: 'Ký túc xá',
    latitude: 16.042153,
    longtitude: 108.522212
  ),
  Motel(
    id: "motel12",
    imageUrl: [
      'assets/images/nhatro15.jpg',
      'assets/images/nhatro11.jpg',
      'assets/images/nhatro8.png',
      'assets/images/nhatro13.jpg',
      'assets/images/nhatro9.jpg',
      'assets/images/nhatro10.jpg',
      'assets/images/nhatro12.jpg',
      'assets/images/nhatro14.jpg',
    ],
    name: '88 đường 2-9',
    address: 'Hải Châu',
    price: 1950000,
    height: 320,
    tags: ['Giá rẻ', 'Nhiều tiện ích', 'Không cần đặt cọc'],
    bossName: 'Lê Đình Trọng',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
    formality: 'Không chung chủ',
    latitude: 16.022253,
    longtitude: 108.1122212
  ),
  Motel(
    id: "motel13",
    imageUrl: [
      'assets/images/nhatro12.jpg',
      'assets/images/nhatro11.jpg',
      'assets/images/nhatro8.png',
      'assets/images/nhatro15.jpg',
      'assets/images/nhatro9.jpg',
      'assets/images/nhatro13.jpg',
      'assets/images/nhatro10.jpg',
      'assets/images/nhatro14.jpg',
    ],
    name: 'K551/15 2-9',
    address: 'Hòa Cường Nam, Hải Châu',
    price: 1680000,
    height: 200,
    tags: ['Hỗ trợ đặt phòng', 'Không cần đặt cọc'],
    bossName: 'Nguyễn Duy Phong',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
    formality: 'Ký túc xá',
    latitude: 16.08253,
    longtitude: 108.21242
  ),
  Motel(
    id: "motel14",
    imageUrl: [
      'assets/images/nhatro1.jpg',
      'assets/images/nhatro9.jpg',
      'assets/images/nhatro10.jpg',
      'assets/images/nhatro11.jpg',
      'assets/images/nhatro12.jpg',
      'assets/images/nhatro13.jpg',
      'assets/images/nhatro14.jpg',
      'assets/images/nhatro15.jpg',
    ],
    name: '26 Hồ Chí Minh',
    address: 'Hải Châu',
    price: 1420000,
    height: 190,
    tags: ['Giá rẻ', 'Nhiều tiện ích', 'Hỗ trợ đặt phòng'],
    bossName: 'Phạm Chí Thoại',
    bossPhone: '0372231124',
    acreage: 25.0,
    mezzanine: 12.0,
    maxPeople: 7,
    waterPrice: 4000,
    deposit: 'Đặt cọc trước 12 tháng',
    formality: 'Không chung chủ',
    latitude: 16.025423,
    longtitude: 108.251212
  ),
];